### ISSUE TITLE
Decoupling the Stream

### ISSUE THREAD

**Issue by jneem** [little-dude/rmp-rpc#11]
Hi! I'm looking for a crate for some msgpack-rpc, and this one looks nice, so thanks for making it!

However, my requirements are a bit different from what this crate provides. Most specifically, I need support for Unix domain sockets. But more generally, I want a crate that abstracts over the Stream type. For example, I'd want the main entry point for a server to be a function with a signature like `connect<S: Stream, B: ServiceBuilder>(stream: S, builder: B) -> impl Future<Item=(), Error=()>` instead of the current `serve` function. The user of my hypothetical ideal crate would be responsible for setting up the `TcpListener` themselves.

Is this sort of change something you'd be interested in accepting a pull request for, or are you committed to keeping TCP support baked into this crate?

**Comment by little-dude** [comment]
Hi,

I'd be very happy to accept such a change. I think this is the way I should have wrote this crate in the first place. Do you need help from me for this?

**Comment by jneem** [comment]
Great! I think I can manage to write a PR for this, but I'll let you know if I get stuck.

**Comment by little-dude** [comment]
Fixed in https://github.com/little-dude/rmp-rpc/pull/12, release in 0.2. Thanks!
