### ISSUE TITLE
Implement timeouts

### ISSUE THREAD

**Issue by little-dude** [little-dude/rmp-rpc#14]
Since we are discussing potential future improvements in https://github.com/little-dude/rmp-rpc/pull/12, I thought I'd open an issue for this.

I'd like to be able to set a timeout to receive a response to a request.

**Comment by jneem** [comment]
You can set a timeout already, by `select`ing the response future with a `tokio_core::reactor::Timeout`, although I admit that's a little awkward.

**Comment by little-dude** [comment]
Ah you're right, I didn't realize it was that easy! Closing then.
